apiVersion: skaffold/v2beta29
kind: Config
build:
  local:
    push: true
  artifacts:
    - image: docker.io/khalilkhalef/java-flux-jib
      jib: {}
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
portForward:
  - resourceType: service
    resourceName: java-flux-jib
    port: 8080
    localPort: 8080
profiles:
  - name: dev
    patches:
      - op: replace
        path: /build/local/push
        value: false