apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-flux
spec:
  selector:
    matchLabels:
      app: java-flux
  replicas: 2
  template:
    metadata:
      labels:
        app: java-flux
    spec:
      containers:
        - name: java-flux
          image: khalilkhalef/java-flux:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3