kind: Service
apiVersion: v1
metadata:
  name: java-flux
spec:
  selector:
    app: java-flux
  ports:
    - name: "8080"
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer